### ISSUE TITLE
Sorry, user icinga is not allowed to execute '/sbin/nologin -c /bin/bash -c /usr/lib64/nagios/plugins/check_fail2ban' as icinga

### ISSUE THREAD

**Issue by LinuxPersonEC** [n1tr0-5urf3r/icinga2-scripts#3]
Similar to [How to run Plugins using director #2130](https://github.com/Icinga/icingaweb2-module-director/issues/2130), on Fedora I get the below warning.
```
icinga2-2.13.1-1.fc34.icinga.x86_64
icingaweb2-2.9.3-1.fc34.icinga.noarch

```

from CLI this works:

```
 '/usr/bin/su' 'icinga' '-s' '/bin/bash' '-c' '/usr/lib64/nagios/plugins/check_fail2ban'
OK: fail2ban running
```

From the GUI

`Sorry, user icinga is not allowed to execute '/sbin/nologin -c /bin/bash -c /usr/lib64/nagios/plugins/check_fail2ban' as icinga on ourserver.edu.`

![sorry](https://user-images.githubusercontent.com/21204619/140970888-f1d69eda-9de1-4704-9dac-481fa211cba0.PNG)

Any work around available? On the master server /etc/sudoers has this:
```
Defaults:icinga !requiretty
icinga ALL=(root) NOPASSWD:/usr/bin/fail2ban-client status
icinga ALL=(root) NOPASSWD:/usr/bin/fail2ban-client status *
icinga ALL=(root) NOPASSWD:/usr/bin/fail2ban-client get * bantime
nagios ALL=(root) NOPASSWD:/usr/bin/fail2ban-client status
nagios ALL=(root) NOPASSWD:/usr/bin/fail2ban-client status *
nagios ALL=(root) NOPASSWD:/usr/bin/fail2ban-client get * bantime
icinga ALL=(root) NOPASSWD:/usr/lib64/nagios/plugins/check_http
```

**Comment by n1tr0-5urf3r** [comment]
I am not really familiar with icinga director as I am running everything without it. 

Some ideas:
- What confuses me the most is the '/sbin/nologin ..' in front of the command from director, is that normal for a command from icinga director? If not, can you change it? 
- As you have the script itself listed in your sudoers file, are you trying to run the script with sudo from the director definition too? You don't need that, the fail2ban commands are run from there with sudo.
- You only need the 'icinga' entries in your /etc/sudoers file if your user is called icinga.
- I assume that the ownership and permissions are set correctly on the script, as you can run the command manually successful

**Comment by LinuxPersonEC** [comment]
> * What confuses me the most is the '/sbin/nologin ..' in front of the command from director, is that normal for a command from icinga director? If not, can you change it?

I had in the Command field  `/usr/bin/sudo -u icinga -s /bin/bash -c  /usr/lib64/nagios/plugins/check_fail2ban`

> * As you have the script itself listed in your sudoers file, are you trying to run the script with sudo from the director definition too?

Yes I was.

Now I'm getting:
```
Plugin Output
OK: fail2ban running
CRITICAL:
Jail: pam-generic
Ban Time: 10800
Currently Banned: 21
[..]
```

But it shows as Critical:
![fai2lban](https://user-images.githubusercontent.com/21204619/140991491-052059d9-ba5f-4670-a906-97d5664b1f0f.PNG)

![plugincheck](https://user-images.githubusercontent.com/21204619/140991518-c0d66be3-6aee-4dbf-98e1-a3772f8df1cb.PNG)

```
zones.d/director-global/commands.conf
object CheckCommand "Fail2ban with sudo" {
    import "plugin-check-command"
    command = [ "/usr/lib64/nagios/plugins/check_fail2ban" ]
}
```

**Comment by n1tr0-5urf3r** [comment]
> 
> 
> > * What confuses me the most is the '/sbin/nologin ..' in front of the command from director, is that normal for a command from icinga director? If not, can you change it?
> 
> I had in the Command field `/usr/bin/sudo -u icinga -s /bin/bash -c /usr/lib64/nagios/plugins/check_fail2ban`
> 
> > * As you have the script itself listed in your sudoers file, are you trying to run the script with sudo from the director definition too?
> 
> Yes I was.
> 
> Now I'm getting:
> 
> ```
> Plugin Output
> OK: fail2ban running
> CRITICAL:
> Jail: pam-generic
> Ban Time: 10800
> Currently Banned: 21
> [..]
> ```
> 
> But it shows as Critical: ![fai2lban](https://user-images.githubusercontent.com/21204619/140991491-052059d9-ba5f-4670-a906-97d5664b1f0f.PNG)
> 
> ![plugincheck](https://user-images.githubusercontent.com/21204619/140991518-c0d66be3-6aee-4dbf-98e1-a3772f8df1cb.PNG)
> 
> ```
> zones.d/director-global/commands.conf
> object CheckCommand "Fail2ban with sudo" {
>     import "plugin-check-command"
>     command = [ "/usr/lib64/nagios/plugins/check_fail2ban" ]
> }
> ```

Then it works as expected :) You can pass the parameter `-c <number>` to increase the threshold. It defaults to 20, so if you have 20 or more banned IPs, it will switch to critical.

**Comment by LinuxPersonEC** [comment]
Cool and I see` -c` needs to come before` -w`. I'm testing `-j` but Director is not passing it via Arguments:

![minusj](https://user-images.githubusercontent.com/21204619/140994917-24ee8e5f-ccb7-45ab-a47b-1977977100aa.PNG)


`./check_fail2ban -h Display this message -w defaults to 10 -c defaults to 20 -t Time: Display until when IPs will be banned -j i.e. comma separated string of jails, i.e. ssh,​postfix Only check those jails Examples: ./check_fail2ban -t -w 5 -c 10 -j ssh,​postfix ./check_fail2ban -t Error: Unknown argument: sshd`

```
Executed Command
'/usr/lib64/nagios/plugins/check_fail2ban' 'sshd'
```

**Comment by n1tr0-5urf3r** [comment]
This might be due to the `skip key True` option maybe, see [here](https://icinga.com/docs/icinga-2/latest/doc/03-monitoring-basics/#command-arguments-skip-key)

**Comment by LinuxPersonEC** [comment]
I figured it out. You have to make sure the position is correct, i.e,. the order of the arguments left to right.` -c` has to come before` -w` and `-j `goes last.

![minusj2](https://user-images.githubusercontent.com/21204619/140997807-8161c0b8-c48d-4590-a571-4d64ef4a15b2.PNG)
![arguments2](https://user-images.githubusercontent.com/21204619/140997810-1f2e74c2-df11-4f88-a687-b392adb47dc6.PNG)

**Comment by n1tr0-5urf3r** [comment]
Thats weird, the order of arguments shouldnt matter. But maybe thats some icinga director specific stuff, glad that you resolved it :)
